name: Deploy MultiDocker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - run: docker build -t abelsantos/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true abelsantos/react-test npm test
      - run: docker build -t abelsantos/multi-client ./client
      - run: docker build -t abelsantos/multi-nginx ./nginx
      - run: docker build -t abelsantos/multi-server ./server
      - run: docker build -t abelsantos/multi-worker ./worker

      - run: docker push abelsantos/multi-client
      - run: docker push abelsantos/multi-nginx
      - run: docker push abelsantos/multi-server
      - run: docker push abelsantos/multi-worker

#      - name: Generate deployment package
#        run: zip -r deploy.zip . -x '*.git*'
#
#      - name: Deploy to EB
#        uses: einaregilsson/beanstalk-deploy@v18
#        with:
#          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
#          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
#          application_name: multi-docker
#          environment_name: Multi-docker-env
#          existing_bucket_name: elasticbeanstalk-eu-central-1-133390731628
#          region: eu-central-1
#          version_label: ${{ github.sha }}
#          deployment_package: deploy.zip
